
TRAIN_SYMBOLS=(
    "BNBUSDT"
    "ADAUSDT"
    "XRPUSDT"
    "DOGEUSDT"
    "DOTUSDT"
    "SOLUSDT"
)

SYMBOL="ADAUSDT"
INTERVAL="5m"
FETCH_N=40000
BATCH=100
PREDICT_FIELD="c"
NORMALIZATION="std"
TRAIN_CYCLES=30

DATA_PATH="data/<SYMBOL>.${INTERVAL}.csv"
TRAINSET_PATH="data/${SYMBOL}.${INTERVAL}.trainset.${BATCH}.csv"
MODEL_PATH="data/${SYMBOL}.${INTERVAL}.${PREDICT_FIELD}.model.${BATCH}.pkl"
